repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black `git diff --cached --name-only`
    # files: git diff --cached --name-only
    language: system
    pass_filenames: True

- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: poetry run flake8 `git diff --cached --name-only`
    # files: git diff --cached --name-only
    language: system
    pass_filenames: True

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: poetry run mypy
    files: git diff --cached --name-only
    language: system
    pass_filenames: True

- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort
    files: git diff --cached --name-only
    language: system
    pass_filenames: True