"""
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
def findTheDifference(s: str, t: str) -> str:
    from collections import Counter
    cnt_s = Counter(s)
    cnt_t = Counter(t)
    skey = set(cnt_s.keys())
    tkey = set(cnt_t.keys())
    res = str()
    if len(cnt_s) != len(cnt_t):
        # print(skey, tkey, skey.symmetric_difference(tkey))
        res = ''.join(skey.symmetric_difference(tkey))
        # print(res)
    else:
        for k in cnt_s.keys():
            if cnt_s[k] != cnt_t[k]:
                res = k
    return res
        